language: node_js

node_js:
  - "4"
  - "5"
  - "6"

sudo: false

script:
 - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#dat"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always

